import React, { useState, useEffect, useMemo } from 'react';
import { Product, ViewState, AppConfig, User } from './types';
import { Login } from './components/Login';
import { ProductList } from './components/ProductList';
import { ProductForm } from './components/ProductForm';
import { Settings } from './components/Settings';
import { UserManagement } from './components/UserManagement';
import { CategoryManagement } from './components/CategoryManagement';
import { UnlockModal } from './components/UnlockModal';
import { initSupabase, fetchProducts, fetchCategories, createProduct, updateProduct, deleteProduct, bulkDeleteProducts, bulkUpdateProductsStock } from './services/supabaseService';
import { deleteImageFromCloudinary } from './services/cloudinaryService';
import { 
  LayoutDashboard, 
  Plus, 
  Settings as SettingsIcon, 
  LogOut, 
  PackageOpen, 
  Loader2, 
  Users, 
  Database, 
  Check, 
  Copy, 
  Lock,
  TrendingUp,
  AlertTriangle,
  Package,
  Tag
} from 'lucide-react';

const LOCAL_STORAGE_KEY = 'putimach_config_v1';
const USERS_STORAGE_KEY = 'putimach_users_v1';

const DEFAULT_USERS: User[] = [
  { id: '1', username: 'sahik', role: 'ADMIN' },
  { id: '2', username: 'putimach', role: 'ADMIN' }
];

const DEFAULT_CONFIG: AppConfig = {
  supabaseUrl: 'https://frwbmnidalsvmvppdzcc.supabase.co',
  supabaseKey: 'sb_publishable_9HDWqfDsJB6V9ufBPI8fhA_nR4v4ioV',
  cloudinaryCloudName: 'dqocdnxbt',
  cloudinaryUploadPreset: 'Putimach'
};

const SQL_SETUP_CODE = `-- FINAL SUPABASE SCHEMA FOR PUTIMACH
-- 1. Create Tables
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT,
  description TEXT,
  "isNew" BOOLEAN DEFAULT true,
  "inStock" BOOLEAN DEFAULT true,
  currency TEXT DEFAULT 'BDT',
  price NUMERIC DEFAULT 0,
  stock NUMERIC DEFAULT 0,
  sizes TEXT[] DEFAULT '{}',
  colors TEXT[] DEFAULT '{}',
  images TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.product_variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
  size TEXT,
  color TEXT,
  price NUMERIC DEFAULT 0,
  stock NUMERIC DEFAULT 0,
  images TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Security (RLS)
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable all access" ON public.categories;
CREATE POLICY "Enable all access" ON public.categories FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Enable all access" ON public.products;
CREATE POLICY "Enable all access" ON public.products FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Enable all access" ON public.product_variants;
CREATE POLICY "Enable all access" ON public.product_variants FOR ALL USING (true) WITH CHECK (true);

-- 3. Optimization
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);
CREATE INDEX IF NOT EXISTS idx_products_name ON public.products(name);
CREATE INDEX IF NOT EXISTS idx_variants_product_id ON public.product_variants(product_id);

-- 4. Reload
NOTIFY pgrst, 'reload schema';`;

const App: React.FC = () => {
  const [currentUser, setCurrentUser] = useState<User | null>(null);
  const [view, setView] = useState<ViewState>(ViewState.LIST);
  const [products, setProducts] = useState<Product[]>([]);
  const [currentProduct, setCurrentProduct] = useState<Product | null>(null);
  const [loading, setLoading] = useState(false);
  const [dbError, setDbError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  
  const [settingsUnlocked, setSettingsUnlocked] = useState(false);
  const [usersUnlocked, setUsersUnlocked] = useState(false);
  const [unlockModalOpen, setUnlockModalOpen] = useState(false);
  const [pendingView, setPendingView] = useState<ViewState | null>(null);
  
  const [users, setUsers] = useState<User[]>(() => {
    const saved = localStorage.getItem(USERS_STORAGE_KEY);
    const existingUsers = saved ? JSON.parse(saved) : DEFAULT_USERS;
    
    // Ensure the required 'putimach' user exists in the saved state
    if (!existingUsers.some((u: User) => u.username.toLowerCase() === 'putimach')) {
      existingUsers.push(DEFAULT_USERS[1]);
    }
    return existingUsers;
  });

  const [config, setConfig] = useState<AppConfig>(() => {
    const saved = localStorage.getItem(LOCAL_STORAGE_KEY);
    if (saved) {
      const parsed = JSON.parse(saved);
      return {
        ...DEFAULT_CONFIG,
        ...parsed
      };
    }
    return DEFAULT_CONFIG;
  });

  useEffect(() => {
    localStorage.setItem(USERS_STORAGE_KEY, JSON.stringify(users));
  }, [users]);

  useEffect(() => {
    if (config.supabaseUrl && config.supabaseKey) {
      initSupabase(config);
      loadProducts();
    }
  }, [config]);

  const stats = useMemo(() => {
    const totalItems = products.length;
    let totalStock = 0;
    let lowStockCount = 0;

    products.forEach(p => {
      const variantsStock = p.variants?.reduce((acc, v) => acc + (v.stock || 0), 0) || 0;
      const effectiveStock = variantsStock > 0 ? variantsStock : (p.stock || 0);
      totalStock += effectiveStock;
      if (effectiveStock < 10) lowStockCount++;
    });

    return { totalItems, totalStock, lowStockCount };
  }, [products]);

  const loadProducts = async () => {
    setLoading(true);
    setDbError(null);
    try {
      const prodsData = await fetchProducts();
      setProducts(prodsData);
    } catch (error: any) {
      console.error("Failed to load data", error);
      if (error?.code === 'PGRST205' || error?.code === 'PGRST200' || error?.code === '42P01' || error?.message?.includes('relation "public.products" does not exist')) {
        setDbError('MISSING_TABLE');
      }
    } finally {
      setLoading(false);
    }
  };

  const handleSaveConfig = (newConfig: AppConfig) => {
    setConfig(newConfig);
    localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(newConfig));
    setView(ViewState.LIST);
  };

  const handleCreateOrUpdate = async (product: Product) => {
    try {
      if (product.id) await updateProduct(product);
      else await createProduct(product);
      await loadProducts();
      setView(ViewState.LIST);
    } catch (error: any) {
      console.error(error);
      if (error?.code === '42P01') setDbError('MISSING_TABLE');
      else alert(`Error saving product: ${error.message || 'Check DB connection'}`);
    }
  };

  const handleDelete = async (id: string | number) => {
    const productToDelete = products.find(p => p.id === id);
    if (!productToDelete) return;

    if (!window.confirm(`PERMANENT DELETE: Are you sure you want to delete "${productToDelete.name}"? This will remove all database records and purge images from Cloudinary.`)) return;
    
    try {
      const allImages = new Set<string>();
      (productToDelete.images || []).forEach(img => allImages.add(img));
      (productToDelete.variants || []).forEach(v => {
        (v.images || []).forEach(img => allImages.add(img));
      });

      await deleteProduct(id);
      setProducts(prev => prev.filter(p => p.id !== id));

      if (allImages.size > 0 && config.cloudinaryApiKey && config.cloudinaryApiSecret) {
        Promise.all(Array.from(allImages).map(url => deleteImageFromCloudinary(url, config)))
          .catch(err => console.error("Cloudinary Cleanup Failed", err));
      }
    } catch (error: any) {
      console.error(error);
      alert(`Delete Failed: ${error.message}`);
    }
  };

  const handleBulkDelete = async (ids: (string | number)[]) => {
    if (!window.confirm(`PERMANENT DELETE: Are you sure you want to delete ${ids.length} products? This action is irreversible.`)) return;
    
    try {
      setLoading(true);
      const allImages = new Set<string>();
      const productsToDelete = products.filter(p => ids.includes(p.id));
      
      productsToDelete.forEach(p => {
        (p.images || []).forEach(img => allImages.add(img));
        (p.variants || []).forEach(v => {
          (v.images || []).forEach(img => allImages.add(img));
        });
      });

      await bulkDeleteProducts(ids);
      setProducts(prev => prev.filter(p => !ids.includes(p.id)));

      if (allImages.size > 0 && config.cloudinaryApiKey && config.cloudinaryApiSecret) {
        Promise.all(Array.from(allImages).map(url => deleteImageFromCloudinary(url, config)))
          .catch(err => console.error("Bulk Cloudinary Cleanup Failed", err));
      }
    } catch (error: any) {
      console.error(error);
      alert(`Bulk Delete Failed: ${error.message}`);
    } finally {
      setLoading(false);
    }
  };

  const handleBulkStatusUpdate = async (ids: (string | number)[], inStock: boolean) => {
    try {
      setLoading(true);
      await bulkUpdateProductsStock(ids, inStock);
      setProducts(prev => prev.map(p => ids.includes(p.id) ? { ...p, inStock } : p));
    } catch (error: any) {
      console.error(error);
      alert(`Bulk Update Failed: ${error.message}`);
    } finally {
      setLoading(false);
    }
  };

  const handleEdit = (product: Product) => {
    setCurrentProduct(product);
    setView(ViewState.EDIT);
  };

  const handleSettingsClick = () => {
    if (settingsUnlocked) setView(ViewState.SETTINGS);
    else { setPendingView(ViewState.SETTINGS); setUnlockModalOpen(true); }
  };

  const handleUsersClick = () => {
    if (usersUnlocked) setView(ViewState.USERS);
    else { setPendingView(ViewState.USERS); setUnlockModalOpen(true); }
  };

  const handleUnlockSuccess = () => {
    if (pendingView === ViewState.SETTINGS) { setSettingsUnlocked(true); setView(ViewState.SETTINGS); }
    else if (pendingView === ViewState.USERS) { setUsersUnlocked(true); setView(ViewState.USERS); }
    setPendingView(null);
  };

  const copySQL = () => {
    navigator.clipboard.writeText(SQL_SETUP_CODE);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!currentUser) return <Login onLogin={setCurrentUser} users={users} />;

  const NavItem = ({ icon: Icon, label, active, onClick, hidden = false }: any) => {
    if (hidden) return null;
    return (
      <button onClick={onClick} className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all font-medium text-sm mb-1 relative overflow-hidden group ${active ? 'text-white bg-blue-500/20 border border-blue-400/20 shadow-[0_0_15px_rgba(59,130,246,0.15)]' : 'text-slate-400 hover:bg-white/5 hover:text-white'}`}>
        {active && <div className="absolute left-0 top-0 bottom-0 w-1 bg-blue-500 shadow-[0_0_10px_#3b82f6]"></div>}
        <Icon className={`w-5 h-5 relative z-10 ${active ? 'text-blue-400' : 'text-slate-500 group-hover:text-white'}`} />
        <span className="relative z-10">{label}</span>
      </button>
    );
  };

  const StatCard = ({ title, value, sub, icon: Icon, color, bg }: any) => (
    <div className="glass-panel p-6 rounded-2xl hover:shadow-lg transition-all duration-300 transform hover:-translate-y-1">
       <div className="flex justify-between items-start mb-4">
          <div className={`p-3 rounded-xl ${bg} backdrop-blur-md`}>
            <Icon className={`w-6 h-6 ${color}`} />
          </div>
          <span className="text-xs font-semibold text-slate-500 bg-white/40 px-3 py-1 rounded-full border border-white/40">{sub}</span>
       </div>
       <h3 className="text-3xl font-bold text-slate-800 mb-1 tracking-tight">{value}</h3>
       <p className="text-sm font-medium text-slate-500">{title}</p>
    </div>
  );

  return (
    <div className="min-h-screen flex font-sans">
      <UnlockModal isOpen={unlockModalOpen} onClose={() => { setUnlockModalOpen(false); setPendingView(null); }} onUnlock={handleUnlockSuccess} title={pendingView === ViewState.SETTINGS ? "Unlock Configuration" : "Unlock User Management"} />
      <aside className="w-72 glass-sidebar text-white fixed h-full hidden md:flex flex-col z-20 shadow-2xl">
        <div className="p-6">
          <div className="flex items-center gap-3 mb-8">
            <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-xl flex items-center justify-center shadow-lg shadow-blue-900/40 ring-1 ring-white/10"><PackageOpen className="w-6 h-6 text-white" /></div>
            <div><span className="font-bold text-xl tracking-tight block text-white/90">Putimach</span></div>
          </div>
          <div className="flex items-center gap-3 bg-white/5 p-3 rounded-xl border border-white/5 backdrop-blur-sm">
             <div className="w-8 h-8 rounded-full bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center text-xs font-bold border border-white/10">{currentUser.username[0].toUpperCase()}</div>
             <div>
               <div className="text-sm font-medium text-white/90">{currentUser.username}</div>
               <div className="text-[10px] text-blue-300 font-semibold uppercase tracking-wider flex items-center gap-1.5"><span className="w-1.5 h-1.5 rounded-full bg-green-400"></span>{currentUser.role}</div>
             </div>
          </div>
        </div>
        <div className="px-4 flex-1 overflow-y-auto">
          <div className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-4 px-4 mt-2">Main Menu</div>
          <nav className="space-y-2">
            <NavItem icon={LayoutDashboard} label="Overview" active={view === ViewState.LIST} onClick={() => setView(ViewState.LIST)} />
            <NavItem icon={Plus} label="Add Product" active={view === ViewState.ADD} onClick={() => { setCurrentProduct(null); setView(ViewState.ADD); }} />
            <NavItem icon={Tag} label="Categories" active={view === ViewState.CATEGORIES} onClick={() => setView(ViewState.CATEGORIES)} />
            <NavItem icon={usersUnlocked ? Users : Lock} label="User Roles" active={view === ViewState.USERS} hidden={currentUser.role !== 'ADMIN'} onClick={handleUsersClick} />
            <NavItem icon={settingsUnlocked ? SettingsIcon : Lock} label="Configuration" active={view === ViewState.SETTINGS} onClick={handleSettingsClick} />
          </nav>
        </div>
        <div className="p-4 border-t border-white/5">
          <button onClick={() => setCurrentUser(null)} className="w-full flex items-center gap-3 px-4 py-3 text-slate-400 hover:text-white hover:bg-white/5 rounded-xl transition-colors text-sm font-medium"><LogOut className="w-5 h-5" />Sign Out</button>
        </div>
      </aside>
      <main className="flex-1 md:ml-72 p-6 md:p-10 max-w-[1600px] w-full mx-auto relative z-10">
        {dbError === 'MISSING_TABLE' && (
           <div className="glass-panel rounded-2xl border-l-4 border-l-orange-500 p-8 mb-8">
             <div className="flex items-start gap-5">
               <div className="bg-orange-100/50 p-4 rounded-full shrink-0"><Database className="w-8 h-8 text-orange-600" /></div>
               <div className="flex-1">
                 <h2 className="text-xl font-bold text-slate-900 mb-2 text-balance">Schema Sync Required</h2>
                 <p className="text-slate-600 mb-6">Your Supabase project is connected, but the required tables are missing. Please run this script in your Supabase SQL Editor to enable all features including sizes, colors, and global media.</p>
                 <div className="bg-slate-900 rounded-xl p-5 mb-6 relative group border border-white/10 shadow-inner">
                   <button onClick={copySQL} className="absolute top-4 right-4 p-2 bg-white/10 hover:bg-white/20 rounded-lg text-white" title="Copy SQL">{copied ? <Check className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4" />}</button>
                   <code className="text-xs text-blue-300 font-mono block overflow-x-auto pb-2">{SQL_SETUP_CODE.split('\n').slice(0, 5).join('\n')}...</code>
                 </div>
                 <div className="flex flex-wrap gap-4 items-center">
                   <a href="https://supabase.com/dashboard" target="_blank" rel="noreferrer" className="px-6 py-2.5 bg-orange-600 text-white font-medium rounded-lg hover:bg-orange-700 transition-colors">Open SQL Editor</a>
                   <button onClick={loadProducts} className="px-6 py-2.5 glass-panel text-slate-700 font-medium rounded-lg hover:bg-white transition-colors">Verify Fix & Retry</button>
                 </div>
               </div>
             </div>
           </div>
        )}
        <div className="animate-in fade-in duration-700 slide-in-from-bottom-4">
          {view === ViewState.LIST && dbError !== 'MISSING_TABLE' && (
            <>
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-10">
                <div>
                  <h1 className="text-4xl font-extrabold text-slate-900 tracking-tight drop-shadow-sm">Inventory Dashboard</h1>
                  <p className="text-slate-500 mt-1 font-medium text-lg">Managing inventory for Putimach</p>
                </div>
                <button onClick={() => { setCurrentProduct(null); setView(ViewState.ADD); }} className="bg-blue-600/90 hover:bg-blue-600 text-white px-6 py-3 rounded-xl font-semibold shadow-lg shadow-blue-600/30 flex items-center gap-2 transform hover:-translate-y-0.5">
                  <Plus className="w-5 h-5" /> Add New Product
                </button>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mb-10">
                 <StatCard title="Total Products" value={stats.totalItems} sub="Unique Items" icon={Package} color="text-blue-600" bg="bg-blue-50/50" />
                 <StatCard title="Total Stock" value={stats.totalStock.toLocaleString()} sub="Units Available" icon={TrendingUp} color="text-purple-600" bg="bg-purple-50/50" />
                 <StatCard title="Low Inventory" value={stats.lowStockCount} sub="Restock Required" icon={AlertTriangle} color="text-orange-600" bg="bg-orange-50/50" />
              </div>
              {loading && products.length === 0 ? <div className="flex flex-col items-center justify-center py-32"><Loader2 className="w-12 h-12 text-blue-600 animate-spin mb-4" /><p className="text-slate-500">Loading catalog...</p></div> : <ProductList products={products} currentUser={currentUser} onEdit={handleEdit} onDelete={handleDelete} onBulkDelete={handleBulkDelete} onBulkStatusUpdate={handleBulkStatusUpdate} />}
            </>
          )}
          {(view === ViewState.ADD || view === ViewState.EDIT) && dbError !== 'MISSING_TABLE' && (
            <div className="max-w-4xl mx-auto"><ProductForm product={currentProduct} config={config} onSubmit={handleCreateOrUpdate} onCancel={() => setView(ViewState.LIST)} /></div>
          )}
          {view === ViewState.CATEGORIES && <CategoryManagement />}
          {view === ViewState.USERS && currentUser.role === 'ADMIN' && <UserManagement users={users} onUpdateUsers={setUsers} />}
          {view === ViewState.SETTINGS && <Settings config={config} onSave={handleSaveConfig} />}
        </div>
      </main>
    </div>
  );
};
export default App;