-- FINAL SUPABASE SCHEMA FOR PUTIMACH
-- Optimized for seamless product management and permanent deletion

-- 1. Create Categories Table
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create Products Table
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT,
  description TEXT,
  "isNew" BOOLEAN DEFAULT true,
  "inStock" BOOLEAN DEFAULT true,
  currency TEXT DEFAULT 'BDT',
  price NUMERIC DEFAULT 0,
  stock NUMERIC DEFAULT 0,
  sizes TEXT[] DEFAULT '{}',
  colors TEXT[] DEFAULT '{}',
  images TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Create Product Variants Table (with CASCADE DELETE)
-- This ensures that when a product is deleted, all its variants are automatically removed.
CREATE TABLE IF NOT EXISTS public.product_variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
  size TEXT,
  color TEXT,
  price NUMERIC DEFAULT 0,
  stock NUMERIC DEFAULT 0,
  images TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;

-- 5. Create Permissive Policies (FOR ALL operations: SELECT, INSERT, UPDATE, DELETE)
-- These allow the Admin Panel to perform any action on the database.
DROP POLICY IF EXISTS "Enable all access" ON public.categories;
CREATE POLICY "Enable all access" ON public.categories FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all access" ON public.products;
CREATE POLICY "Enable all access" ON public.products FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all access" ON public.product_variants;
CREATE POLICY "Enable all access" ON public.product_variants FOR ALL USING (true) WITH CHECK (true);

-- 6. Performance Optimization Indexes
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);
CREATE INDEX IF NOT EXISTS idx_products_name ON public.products(name);
CREATE INDEX IF NOT EXISTS idx_variants_product_id ON public.product_variants(product_id);

-- 7. Ensure CASCADE DELETE is active if table already existed
-- Sometimes foreign keys are created without ON DELETE CASCADE. This block fixes it.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'product_variants_product_id_fkey'
    ) THEN
        ALTER TABLE public.product_variants 
        DROP CONSTRAINT product_variants_product_id_fkey,
        ADD CONSTRAINT product_variants_product_id_fkey 
        FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
    END IF;
END $$;

-- 8. Final Cache Refresh
NOTIFY pgrst, 'reload schema';