import React, { useState } from 'react';
import { AppConfig } from '../types';
import { Save, AlertCircle, Copy, Check, Database, Eye, EyeOff, ShieldAlert } from 'lucide-react';

interface SettingsProps {
  config: AppConfig;
  onSave: (config: AppConfig) => void;
}

export const Settings: React.FC<SettingsProps> = ({ config, onSave }) => {
  const [localConfig, setLocalConfig] = useState<AppConfig>(config);
  const [message, setMessage] = useState<{ text: string; type: 'success' | 'error' } | null>(null);
  const [copied, setCopied] = useState(false);
  const [showConfig, setShowConfig] = useState(!config.supabaseUrl || !config.supabaseKey);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setLocalConfig(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSave(localConfig);
    setMessage({ text: "Configurations updated!", type: 'success' });
    setTimeout(() => setMessage(null), 3000);
  };

  const sqlCode = `-- FINAL SUPABASE SCHEMA FOR PUTIMACH
-- 1. Create Tables
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT,
  description TEXT,
  "isNew" BOOLEAN DEFAULT true,
  "inStock" BOOLEAN DEFAULT true,
  currency TEXT DEFAULT 'BDT',
  price NUMERIC DEFAULT 0,
  stock NUMERIC DEFAULT 0,
  sizes TEXT[] DEFAULT '{}',
  colors TEXT[] DEFAULT '{}',
  images TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.product_variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
  size TEXT,
  color TEXT,
  price NUMERIC DEFAULT 0,
  stock NUMERIC DEFAULT 0,
  images TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Security (RLS)
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable all access" ON public.categories;
CREATE POLICY "Enable all access" ON public.categories FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Enable all access" ON public.products;
CREATE POLICY "Enable all access" ON public.products FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Enable all access" ON public.product_variants;
CREATE POLICY "Enable all access" ON public.product_variants FOR ALL USING (true) WITH CHECK (true);

-- 3. Optimization
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);
CREATE INDEX IF NOT EXISTS idx_products_name ON public.products(name);
CREATE INDEX IF NOT EXISTS idx_variants_product_id ON public.product_variants(product_id);

-- 4. Reload
NOTIFY pgrst, 'reload schema';`;

  const copySQL = () => {
    navigator.clipboard.writeText(sqlCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex justify-end">
        <button onClick={() => setShowConfig(!showConfig)} className="flex items-center gap-2 text-xs font-medium text-slate-500 hover:text-slate-800 transition-colors bg-white px-3 py-2 rounded-lg border border-slate-200">
          {showConfig ? <><EyeOff className="w-3 h-3" /> Hide Keys</> : <><Eye className="w-3 h-3" /> Show Keys</>}
        </button>
      </div>

      {showConfig && (
        <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-8 animate-in fade-in slide-in-from-top-4">
          <div className="flex items-center gap-3 mb-6 border-b border-slate-100 pb-4">
            <div className="bg-blue-100 p-2 rounded-lg"><Save className="w-6 h-6 text-blue-600" /></div>
            <h2 className="text-xl font-bold text-slate-800">Connection Settings</h2>
          </div>
          {message && <div className="p-4 mb-6 rounded-lg flex items-center gap-2 bg-green-50 text-green-700"><AlertCircle className="w-5 h-5" /><span>{message.text}</span></div>}
          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="space-y-4">
              <h3 className="text-sm font-semibold text-slate-500 uppercase flex items-center gap-2">
                Supabase
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Project URL</label>
                  <input type="text" name="supabaseUrl" value={localConfig.supabaseUrl} onChange={handleChange} className="w-full px-4 py-2.5 rounded-lg border border-slate-300 outline-none text-sm" placeholder="https://..." />
                </div>
                <div>
                  <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Anon / Publishable Key</label>
                  <input type="password" name="supabaseKey" value={localConfig.supabaseKey} onChange={handleChange} className="w-full px-4 py-2.5 rounded-lg border border-slate-300 outline-none text-sm" placeholder="sb_..." />
                </div>
              </div>
            </div>
            
            <div className="pt-6 border-t border-slate-100 space-y-4">
              <div className="flex justify-between items-center">
                <h3 className="text-sm font-semibold text-slate-500 uppercase">Cloudinary</h3>
                <div className="flex items-center gap-1.5 text-[10px] font-bold text-amber-600 bg-amber-50 px-2 py-0.5 rounded border border-amber-200">
                  <ShieldAlert className="w-3 h-3" />
                  PERMANENT DELETE ENABLED
                </div>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Cloud Name</label>
                  <input type="text" name="cloudinaryCloudName" value={localConfig.cloudinaryCloudName} onChange={handleChange} className="w-full px-4 py-2.5 rounded-lg border border-slate-300 outline-none text-sm" />
                </div>
                <div>
                  <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Upload Preset</label>
                  <input type="text" name="cloudinaryUploadPreset" value={localConfig.cloudinaryUploadPreset} onChange={handleChange} className="w-full px-4 py-2.5 rounded-lg border border-slate-300 outline-none text-sm" />
                </div>
                <div>
                  <label className="block text-xs font-bold text-slate-500 uppercase mb-1">API Key (Required for Delete)</label>
                  <input type="text" name="cloudinaryApiKey" value={localConfig.cloudinaryApiKey || ''} onChange={handleChange} className="w-full px-4 py-2.5 rounded-lg border border-slate-300 outline-none text-sm" placeholder="812..." />
                </div>
                <div>
                  <label className="block text-xs font-bold text-slate-500 uppercase mb-1">API Secret (Required for Delete)</label>
                  <input type="password" name="cloudinaryApiSecret" value={localConfig.cloudinaryApiSecret || ''} onChange={handleChange} className="w-full px-4 py-2.5 rounded-lg border border-slate-300 outline-none text-sm" placeholder="••••••••" />
                </div>
              </div>
              <p className="text-[11px] text-slate-400 italic">API Key and Secret are only required if you want the admin panel to permanently remove files from your Cloudinary storage when a product is deleted.</p>
            </div>

            <div className="pt-6"><button type="submit" className="w-full bg-slate-900 hover:bg-slate-800 text-white font-bold py-3.5 rounded-xl transition-all flex items-center justify-center gap-2 shadow-lg shadow-slate-900/20 active:scale-[0.98]"><Save className="w-5 h-5" />Save Configuration</button></div>
          </form>
        </div>
      )}

      <div className="bg-slate-900 rounded-xl shadow-lg border border-slate-800 p-8 text-white">
         <div className="flex items-center gap-3 mb-6">
            <div className="bg-white/10 p-2 rounded-lg"><Database className="w-6 h-6 text-blue-400" /></div>
            <div><h2 className="text-xl font-bold">SQL Schema (Required)</h2><p className="text-slate-400 text-sm">Use this to ensure your database supports all modern Putimach features.</p></div>
         </div>
         <div className="relative group">
            <button onClick={copySQL} className="absolute top-4 right-4 p-2 bg-white/10 hover:bg-white/20 rounded text-white" title="Copy SQL">{copied ? <Check className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4" />}</button>
            <pre className="bg-black/50 p-6 rounded-xl font-mono text-xs text-blue-300 overflow-x-auto border border-white/5">{sqlCode}</pre>
         </div>
      </div>
    </div>
  );
};